- name: Create VM interface 
  hosts: all
  gather_facts: yes
  tasks:
    - name: install ifupdown
      apt: name=ifupdown
    - name: create /etc/network/interfaces
      template: src="~/project/ansible/templates/interfaces.j2" dest=/etc/network/interfaces

