- hosts: all
  tasks: 
  - name: Install quagga
    apt: name=quagga state=latest
  - name: line insert
    lineinfile:
      path: /etc/sysctl.conf
      line: 'net.ipv4.ip_forward=1'
      insertbefore: BOF
  - name: line insert
    lineinfile:
      path: /etc/environment
      line: 'YSH_PAGER=more'
      insertbefore: BOF
<<<<<<< HEAD
- hosts: VM1
  tasks:
  - name: zebra
    template: src=zebra_VM1.txt dest=/etc/quagga/zebra.conf
  - name: ospfd
    template: src=ospfd_VM1.txt dest=/etc/quagga/ospfd.conf
- hosts: VM2
  tasks:
  - name: zebra
    template: src=zebra_VM2.txt dest=/etc/quagga/zebra.conf
  - name: ospfd
    template: src=ospfd_VM2.txt dest=/etc/quagga/ospfd.conf
- hosts: VM3
  tasks:
  - name: zebra
    template: src=zebra_VM3.txt dest=/etc/quagga/zebra.conf
  - name: ospfd
    template: src=ospfd_VM3.txt dest=/etc/quagga/ospfd.conf
- hosts: VM4
  tasks:
  - name: zebra
    template: src=zebra_VM4.txt dest=/etc/quagga/zebra.conf
  - name: ospfd
    template: src=ospfd_VM4.txt dest=/etc/quagga/ospfd.conf

- hosts: all  
  remote_user: root
  tasks:
=======
  - name: line insert
    lineinfile:
      path: /etc//bash.bashrc
      line: 'export VTYSH_PAGER=more'
      insertbefore: BOF
  - name: create /etc/quagga/zebra.conf
    template: src="{{local_zebra_path}}" dest=/etc/quagga/zebra.conf
  - name: create /etc/quagga/ospfd.conf
    template: src="{{local_ospfd_path}}" dest=/etc/quagga/ospfd.conf
>>>>>>> 4VMs_Quagga_Ansible
  - name: line insert
    lineinfile:
      path: '/etc/netplan/50-cloud-init.yaml'
      line: '.disable'
  - name: Touch a file
    file:
      path: '/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg'
      state: touch
  - name: line insert
    lineinfile:
      path: '/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg'
      line: 'network: {config: disabled} '
  - name: Start ospfd
    service:
      name: ospfd
      state: started
  - name: Start zebra
    service:
      name: zebra
      state: started
<<<<<<< HEAD
  - name: Restart network
    service:
      name: network
      state: restarted
=======
>>>>>>> 4VMs_Quagga_Ansible
  - name: reboot the machine
    reboot:
