- hosts: all
  remote_user: root
  tasks: 

  - name: Install quagga
    apt: name=quagga state=latest
  - name: line insert
    lineinfile:
      path: /etc/sysctl.conf
      line: 'net.ipv4.ip_forward=1'
      insertbefore: BOF
  - name: line insert
    lineinfile:
      path: /etc/environment
      line: 'YSH_PAGER=more'
      insertbefore: BOF
  - name: line insert
    lineinfile:
      path: /etc//bash.bashrc
      line: 'export VTYSH_PAGER=more'
      insertbefore: BOF
  - name: line insert
    lineinfile:
      path: /etc//bash.bashrc
      line: 'export VTYSH_PAGER=more'
      insertbefore: BOF

- hosts: VM1
  remote_user: root
  tasks:
  - name: zebra
    template: src=zebra_VM1.txt dest=/etc/quagga/zebra.conf
  - name: ospfd
    template: src=ospfd_VM1.txt dest=/etc/quagga/ospfd.conf
- hosts: VM2
  remote_user: root
  tasks:
  - name: zebra
    template: src=zebra_VM2.txt dest=/etc/quagga/zebra.conf
  - name: ospfd
    template: src=ospfd_VM2.txt dest=/etc/quagga/ospfd.conf
- hosts: VM3
  remote_user: root
  tasks:
  - name: zebra
    template: src=zebra_VM3.txt dest=/etc/quagga/zebra.conf
  - name: ospfd
    template: src=ospfd_VM3.txt dest=/etc/quagga/ospfd.conf
- hosts: VM4
  remote_user: root
  tasks:
  - name: zebra
    template: src=zebra_VM4.txt dest=/etc/quagga/zebra.conf
  - name: ospfd
    template: src=ospfd_VM4.txt dest=/etc/quagga/ospfd.conf

- hosts: all
  remote_user: root
  tasks:
  - name: line insert
    lineinfile:
      path: /etc/netplan/50-cloud-init.yaml
      line: '.disable'
  - name: line insert
    lineinfile:
      path: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
      line: 'network: {config: disabled} '
  - name: Start ospfd
    service:
      name: ospfd
      state: started
  - name: Start zebra
    service:
      name: zebra
      state: started
  - name: service networking restart
    service:
      name: service networking
      state: restarted
  - name: reboot the machine
    reboot:
