- hosts: all
  tasks: 
  - name: Install quagga
    apt: name=quagga state=latest
  - name: line insert
    lineinfile:
      path: /etc/sysctl.conf
      line: 'net.ipv4.ip_forward=1'
      insertbefore: BOF
  - name: line insert
    lineinfile:
      path: /etc/environment
      line: 'YSH_PAGER=more'
      insertbefore: BOF
  - name: line insert
    lineinfile:
      path: /etc/bash.bashrc
      line: 'export VTYSH_PAGER=more'
      insertbefore: BOF
  - name: create /etc/quagga/zebra.conf
    template:
      src: 'zebra.j2'
      dest: /etc/quagga/zebra.conf
  - name: create '/etc/quagga/ospfd.conf'
    template:
      src: 'ospfd.j2'
      dest: '/etc/quagga/ospfd.conf'
  - name: line insert
    lineinfile:
      path: '/etc/netplan/50-cloud-init.yaml'
      line: '.disable'
  - name: Touch a file
    file:
      path: '/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg'
      state: touch
  - name: line insert
    lineinfile:
      path: '/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg'
      line: 'network: {config: disabled} '
  - name: Restarting Network
    service:
      name: networking
      state: restarted
  - name: Start ospfd
    service:
      name: ospfd
      state: started
  - name: Start zebra
    service:
      name: zebra
      state: started
  - name: reboot the machine
    reboot:
