VM1 ansible_host=192.168.122.11 ansible_user=ubuntu ansible_sudo=yes ansible_become=yes
VM2 ansible_host=192.168.122.22 ansible_user=ubuntu ansible_sudo=yes ansible_become=yes
VM3 ansible_host=192.168.122.33 ansible_user=ubuntu ansible_sudo=yes ansible_become=yes
VM4 ansible_host=192.168.122.44 ansible_user=ubuntu ansible_sudo=yes ansible_become=yes

[ubuntu]
VM1
VM2
VM3
VM4


